[project]
name = "my-docs"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mkdocs-material",
    "mkdocs-git-revision-date-localized-plugin",
    "mkdocs-minify-plugin",
    "pymdown-extensions",
    "pyyaml>=6.0.2",
]
